### ISSUE TITLE
Add the ability to add a Channel Avatar when creating a channel

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#118]
1. Right now, we use a default avatar when a new channel is created, give the user the option to be able to upload an avatar when creating a new avatar. If the avatar is not supplied, then the channel should be given a default suya avatar like what's there currently.

<img width="1111" alt="screen shot 2016-01-14 at 6 55 32 am" src="https://cloud.githubusercontent.com/assets/2946769/12316890/f7e4ebe6-ba8b-11e5-9a40-7cddbd08f75f.png">
1. Also implement this in the edit functionality for a channel, someone should be able to upload a picture at a later time, if he/she is tired of the default suya/nyamachoma avatar.

<img width="1111" alt="screen shot 2016-01-14 at 7 00 43 am" src="https://cloud.githubusercontent.com/assets/2946769/12316948/9f997ce4-ba8c-11e5-98d8-50ed8207a326.png">

**Comment by fokosun** [comment]
Ideally, Channels do not require a cover image. @andela-eosuagwu must have put them there just as a place holder. I think it should be removed altogether.
