### ISSUE TITLE
Make the dashboard more responsive

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#119]
Right now, this is the way it looks on my system. Can you see the overlap because of the title of the most recent channel?

<img width="1109" alt="screen shot 2016-01-14 at 7 00 19 am" src="https://cloud.githubusercontent.com/assets/2946769/12316974/cafab33a-ba8c-11e5-8b6c-62415a526026.png">

**Comment by fokosun** [comment]
Yes, there is an overlap. First, i will have to remove the cover images as it's not necessary here. The channels will be displayed in a responsive table instead.
