### ISSUE TITLE
Immediately I merged your last PR, we started getting this error

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#145]
1. An admin can't access his dashboard because of this error now

<img width="1116" alt="screen shot 2016-01-28 at 5 40 01 pm" src="https://cloud.githubusercontent.com/assets/2946769/12651599/7464f48e-c5e7-11e5-9436-ddbb5314af9e.png">
1. When a user tries to comment, it redirects to a `/comment` route where it shows a json response :cry: 

<img width="1119" alt="screen shot 2016-01-28 at 5 48 42 pm" src="https://cloud.githubusercontent.com/assets/2946769/12651634/a6381ffe-c5e7-11e5-97e2-52eca287f6b1.png">

Please fix

**Comment by ibonly** [comment]
The error comes up as a result of how the template is implemented. `top-nav` is used to serve the mobile navigation for both `dashboard` and `registered user`. That is the reason for the error, I will have to separate the mobile navigation.
