### ISSUE TITLE
Little adjustment with login and signup

### ISSUE THREAD

**Issue by ademola-raimi** [andela/suyabay#159]
I am proposing that we let the users have the ability to log in and sign up using their Gmail account. This makes the users have a better experience on the suyabay web app. Unlike the login/sign-out implementation we have currently:

![screen shot 2016-02-16 at 5 04 25 pm](https://cloud.githubusercontent.com/assets/14159420/13082246/2af645da-d4d0-11e5-9361-69330d733a68.png)

![screen shot 2016-02-16 at 5 04 48 pm](https://cloud.githubusercontent.com/assets/14159420/13082247/2afefaea-d4d0-11e5-857a-6192bc9c8527.png)

We could have it like this:
![screen shot 2016-02-16 at 5 28 15 pm](https://cloud.githubusercontent.com/assets/14159420/13082959/2f592284-d4d3-11e5-9966-273f19a1b375.png)

![screen shot 2016-02-16 at 5 28 28 pm](https://cloud.githubusercontent.com/assets/14159420/13082958/2f58c686-d4d3-11e5-9c2f-aa9ce1a70379.png)

**Comment by unicodeveloper** [comment]
Please expatiate on this. It should be very descriptive and well detailed. Right now, the user can signup and login with a gmail account

**Comment by unicodeveloper** [comment]
Right now we already have social media logins for facebook and twitter. At a later time we might add Gmail login but for now, this is what the stakeholders want.

I'll close this issue now.
