### ISSUE TITLE
Quick fix on episode detail page

### ISSUE THREAD

**Issue by olotintemitope** [andela/suyabay#160]
The "comment" label on the episode view could be shifted to the right-hand side, and replaced with "view comments" so that the user can understand where to view comments.

**Comment by unicodeveloper** [comment]
Please expatiate on this and include pictures to better convey your thoughts.

**Comment by olotintemitope** [comment]
The comments display on Suyabay should resemble that of facebook. Where all comments are highlighted and visitors do not need to click view to see all episode comments.

**Comment by unicodeveloper** [comment]
So which task are you working on now?. This?

**Comment by olotintemitope** [comment]
Currently, I'm going through dates, mutators and scope video tutorial on Laracast; to foster my knowledge on Laravel. So that I will be able to work effectively on Suyabay.

**Comment by unicodeveloper** [comment]
..but you have current pending issues to work on, don't you? @andela-tolotin

**Comment by olotintemitope** [comment]
@unicodeveloper Yes, I have episodes comment display to fix on Suyabay.
