### ISSUE TITLE
The Project should have a nice Favicon

### ISSUE THREAD

**Issue by ademola-raimi** [andela/suyabay#161]
It would be great to have Favicon on the app

**Comment by unicodeveloper** [comment]
Are you sure we don't have a favicon?

<img width="1083" alt="screen shot 2016-02-16 at 3 45 20 pm" src="https://cloud.githubusercontent.com/assets/2946769/13079436/7f0997dc-d4c4-11e5-82c9-b77b1b540389.png">

..or do you mean having another favicon, probably finer/better than this?

**Comment by ademola-raimi** [comment]
I can't find Favicon on my browser and on laztopaz's browser as well
![screen shot 2016-02-16 at 3 52 53 pm](https://cloud.githubusercontent.com/assets/14159420/13079800/3d4e3dbe-d4c6-11e5-8b66-e2017d9e8b1c.png)

**Comment by unicodeveloper** [comment]
Please check it on three other systems, let's see the results

**Comment by ademola-raimi** [comment]
I have checked it on six different systems with different browsers, the results are the same

**Comment by unicodeveloper** [comment]
Wow, that's interesting!. Alright, that's another task you should take care of. I'm assigning it to you now
