### ISSUE TITLE
A little adjustment on the Navbar dropdown settings

### ISSUE THREAD

**Issue by ademola-raimi** [andela/suyabay#162]
When the Navbar dropdown settings item is clicked, It displays settings on a white background as shown below;

![screen shot 2016-02-16 at 3 52 53 pm](https://cloud.githubusercontent.com/assets/14159420/13080851/c54d8252-d4ca-11e5-8c1f-566365f674c7.png)

The white background is too big, and It covers some contents on the web as shown above. 

I propose that we have a drop-down similar to the one below:

![screen shot 2016-02-16 at 3 52 31 pm](https://cloud.githubusercontent.com/assets/14159420/13081050/910223a8-d4cb-11e5-835f-9e2300a5d283.png)

**Comment by unicodeveloper** [comment]
Please expatiate on this. It should be very descriptive and well detailed.
