### ISSUE TITLE
List items on the left sidebar of the inner pages needs a valid web address.

### ISSUE THREAD

**Issue by olotintemitope** [andela/suyabay#165]
The lists on the left sidebar of the episode view don't have an address attached to it. When the user 

clicks on any item on the list, it doesn't respond to the click due to the fact that the href property of the a 

tag doesn't have an address.

**Comment by unicodeveloper** [comment]
This issue hasn't been fixed yet. On the landing page, the links are active, but on the `episodes` [page](http://suyabay-staging.herokuapp.com/episodes), they are still dead links, are both pages not referencing the same sidebar template? @andela-tolotin 

<img width="1117" alt="screen shot 2016-03-11 at 7 04 52 am" src="https://cloud.githubusercontent.com/assets/2946769/13694667/ebffea94-e757-11e5-9125-53b06c425675.png">
