### ISSUE TITLE
Adjustments needed on episode comments display

### ISSUE THREAD

**Issue by olotintemitope** [andela/suyabay#166]
The episode comments were hidden and do not give users the impression to either view  or make comments on the episode. Therefore, suggestions were raised during code review that we should adopt facebook style of displaying comments.
![screen shot 2016-02-16 at 4 29 12 pm](https://cloud.githubusercontent.com/assets/14159435/13080830/ae4ff1ca-d4ca-11e5-8a03-bf63bd0e4181.png)

**Comment by olotintemitope** [comment]
@unicodeveloper #160 is an old issue on Suyabay. During the last code review session, we adopted facebook style of displaying comments. Which I'm about working on, so  #166 is the current issue, not #160.

**Comment by unicodeveloper** [comment]
I will need an estimate for this

**Comment by unicodeveloper** [comment]
What's the status on this @andela-tolotin ?

**Comment by olotintemitope** [comment]
@unicodeveloper I have implemented the view episode comments. It displays 10 comments on page load, and also, displays a link where the user can load more comments after clicking on the view comments.

**Comment by unicodeveloper** [comment]
Apparently, none of that works, so you need to check what you did before I assume that you are a `Lying Programmer`

**Comment by olotintemitope** [comment]
@unicodeveloper I have implemented it. Below is the screenshot on the implementation on my local machine.
![screen shot 2016-02-29 at 5 55 27 pm](https://cloud.githubusercontent.com/assets/14159435/13401775/d10e4dd6-df0d-11e5-94ee-ca730f1ec8bc.png)

**Comment by olotintemitope** [comment]
@unicodeveloper  I will make new pull request.

**Comment by unicodeveloper** [comment]
No one is gonna use it on your local machine @andela-tolotin
