### ISSUE TITLE
View not consistent

### ISSUE THREAD

**Issue by ibonly** [andela/suyabay#167]
This is the `settings` view
<img width="1280" alt="screen shot 2016-02-16 at 5 28 55 pm" src="https://cloud.githubusercontent.com/assets/7251019/13083028/8a8e54b2-d4d3-11e5-8dd8-69af2219af90.png">
And this is `account settings` view
<img width="1257" alt="screen shot 2016-02-16 at 5 29 08 pm" src="https://cloud.githubusercontent.com/assets/7251019/13083034/8ec6bb78-d4d3-11e5-8475-ee907145ce98.png">
Why is the `side nav` missing?

**Comment by unicodeveloper** [comment]
The `sidenav` is also now missing for profile

<img width="1118" alt="screen shot 2016-02-29 at 11 14 20 am" src="https://cloud.githubusercontent.com/assets/2946769/13391607/af6895a2-ded5-11e5-8458-37c29faf72d7.png">

**Comment by ademola-raimi** [comment]
I will fix this bug @unicodeveloper and @andela-iadeniyi
