### ISSUE TITLE
Refactoring to ensure that the project has just one master page that all other pages extend from.

### ISSUE THREAD

**Issue by ademola-raimi** [andela/suyabay#173]
It was observed that the Login, Signup and settings pages all extend from different masters layout. This goes against DRY principle. All pages must extend from one master page in order for the principle of DRY not to be violated.

**Comment by unicodeveloper** [comment]
This has been resolved right @andela-araimi ?

**Comment by ademola-raimi** [comment]
Yes, it has been resolved.
