### ISSUE TITLE
[Tests][#114771085] Test the Channel's controller methods.

### ISSUE THREAD

**Issue by johnkariuki** [andela/suyabay#182]
Assert that the model performs the following channel tasks.
1. index() - show all channels.
2.  active() - view all active channels
3. deleted() show deleted channels.
4. list, edit, update and destroy channels.

**Comment by unicodeveloper** [comment]
What's the latest on this @andela-jkariuki ?

**Comment by unicodeveloper** [comment]
You need to reply to this issue @andela-jkariuki
