### ISSUE TITLE
Episodes that have no comments breaks the app

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#203]
Once you click on an episode that does not have comments, the app breaks. @andela-tolotin you worked on this, why does this happen?

<img width="1102" alt="screen shot 2016-03-11 at 7 03 35 am" src="https://cloud.githubusercontent.com/assets/2946769/13694712/5cfb54e0-e758-11e5-84a8-2c8a5bd20c6b.png">

**Comment by olotintemitope** [comment]
@unicodeveloper I have resolved this issue in the new pull request submitted earlier. I will fix the merge conflict so that it can fix this bug.

**Comment by unicodeveloper** [comment]
Which PR?..you should reference the PR in your comment @andela-tolotin

**Comment by olotintemitope** [comment]
@unicodeveloper I have solved this in PR #201

**Comment by olotintemitope** [comment]
@unicodeveloper this issue has been resolved, I think we should close it.
