### ISSUE TITLE
A channel that has no episode should have an appropriate message to display to users

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#204]
Right now, this is what is displayed when an admin clicks on a channel that has no episode.

It would be very intuitive if we can have it display an appropriate message like:

`Ooops, there are no episodes in this channel`

<img width="1114" alt="screen shot 2016-03-11 at 7 02 57 am" src="https://cloud.githubusercontent.com/assets/2946769/13694736/a310e6d4-e758-11e5-9cce-ee30a61883f3.png">

**Comment by johnkariuki** [comment]
@unicodeveloper I have made a PR to fix this issue. screenshots on the fix included too.
