### ISSUE TITLE
Updating user profile

### ISSUE THREAD

**Issue by fokosun** [andela/suyabay#223]
@andela-cvundi 
currently, a user can enter empty string as username and update. The consequence of this is once the user's session expires, the user will never be able to sign in to that account again because username field has been  set to empty. You should address this in your update user profile code.

Happy coding.

**Comment by vickris** [comment]
Cool will fix this

**Comment by johnkariuki** [comment]
@unicodeveloper 
When a user tries to update a username, we check that the username is not blank and also that it is unique.
If it is blank or non uniquer, an error message is shown.

**Comment by unicodeveloper** [comment]
This issue has been fixed, so I'll be closing this issue
