### ISSUE TITLE
Page reloads when an episode is been unfavorited in the landing page

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#224]
The act of unfavoriting an episode shouldnt cause a page reload.

**Comment by unicodeveloper** [comment]
There is still an issue with unfavoriting in the favorites section. If I unfavorite the last episode in the section, it doesn't go away, another episode goes away instead. How does that happen @andela-cvundi ?

I unfavorited Ms Bethsy
<img width="849" alt="screen shot 2016-03-21 at 9 49 35 pm" src="https://cloud.githubusercontent.com/assets/2946769/13933790/337608ae-efaf-11e5-8eac-2f84439fa8b8.png">

Now, it ws Ms Eula that disappeared still living Ms Bethsy

<img width="854" alt="screen shot 2016-03-21 at 9 49 51 pm" src="https://cloud.githubusercontent.com/assets/2946769/13933840/670270c2-efaf-11e5-9d43-34b8614e3f90.png">

Please look into this critically @andela-cvundi

**Comment by vickris** [comment]
This is funny. Just noticed this happens but not all the time. Just revert the PR I will look into the issue.
