### ISSUE TITLE
An admin can create an empty channel without a title and a description

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#227]
An admin can create a channel with no title and description, just empty fields and it goes ahead to create.

This shouldn't be the case, the admin must provide a title and a description.

<img width="1116" alt="screen shot 2016-03-21 at 7 09 49 pm" src="https://cloud.githubusercontent.com/assets/2946769/13929121/dff7c57a-ef98-11e5-9298-2e328b447d94.png">

<img width="1114" alt="screen shot 2016-03-21 at 7 12 02 pm" src="https://cloud.githubusercontent.com/assets/2946769/13929137/f260de9a-ef98-11e5-9ee9-001c0335d6d8.png">

<img width="855" alt="screen shot 2016-03-21 at 7 12 14 pm" src="https://cloud.githubusercontent.com/assets/2946769/13929142/fa90d322-ef98-11e5-8a60-7a703a85ea64.png">

**Comment by johnkariuki** [comment]
Alright. I will add the validation for this @unicodeveloper

**Comment by johnkariuki** [comment]
The issue has been resolved @unicodeveloper .
In addition to the create channel, the same bug was seen on the update channel page where a user can update a channel to have an empty field. 
See PR description for how to test the bug fix and screenshots of the same.
