### ISSUE TITLE
Clean up faulty indentation and inconsistent naming of variables

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#228]
Clean up faulty and inconsistent indentation in [like.js](https://github.com/andela/suyabay/blob/staging/public/js/like.js), same with the naming of variables and add semicolons to the statements that presently have no semicolons.

**Comment by johnkariuki** [comment]
I have been fixing js inconsistency issues on [admin.js.](https://github.com/andela/suyabay/blob/staging/public/js/admin.js) I will work on this too @unicodeveloper

**Comment by unicodeveloper** [comment]
If you can decide to fix inconsistencies on all the js files on this project, it will be much appreciated @andela-jkariuki
