### ISSUE TITLE
The Admin Page states that there are currently 23 users on the platform, the account/users show only 10

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#230]
The Users tab under the Account tab by the admin sidebar shows only 10 user, meanwhile on the Admin dashboard, it boldly states that there are 23 users. How is this possible?

Please find out and fix. All users on the platform should have their profile show up in the Account users table.

<img width="818" alt="screen shot 2016-03-21 at 7 41 43 pm" src="https://cloud.githubusercontent.com/assets/2946769/13930026/6bed9916-ef9d-11e5-90ca-3706f19c7a2a.png">

**Comment by unicodeveloper** [comment]
Please take care of this @andela-jkariuki

**Comment by johnkariuki** [comment]
Alright, will fix it @unicodeveloper .

**Comment by johnkariuki** [comment]
I will also be making another PR on the JS issue. I noticed I broke something in loginAndSignUp js file

**Comment by unicodeveloper** [comment]
Please do submit a hotfix for what you broke ASAP @andela-jkariuki . Then go ahead and work on the original issue.

**Comment by johnkariuki** [comment]
This has been fixed and good for merging. @unicodeveloper
