### ISSUE TITLE
Invitation is been sent on an empty username field

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#231]
Without inputing a username, it allows me to send an upgrade invitation to a nobody. 

An appropriate error message should be thrown if no username is entered into the username field.

<img width="1117" alt="screen shot 2016-03-21 at 7 57 08 pm" src="https://cloud.githubusercontent.com/assets/2946769/13930444/4b4d0d2a-ef9f-11e5-851b-12286096a184.png">

**Comment by unicodeveloper** [comment]
Please take care of this @andela-cvundi

**Comment by vickris** [comment]
Ok...cool
