### ISSUE TITLE
Increase the distance between the edit and delete icons when one opens the comment menu

### ISSUE THREAD

**Issue by vickris** [andela/suyabay#237]
Currently, the distance between the edit and delete comment icons is so small that one can accidentally click on the wrong icon. This should not be case, there should be some distance between the two icons.
<img width="1006" alt="screen shot 2016-03-23 at 6 58 52 pm" src="https://cloud.githubusercontent.com/assets/8840187/13991464/58c37468-f129-11e5-997a-22279ff71fe5.png">

**Comment by vickris** [comment]
Fixed this in another PR. This was a minor change so I did not create a PR for it. Increased the margin between the icons, so the icons now look like this @unicodeveloper 

<img width="1004" alt="screen shot 2016-04-01 at 10 11 22 am" src="https://cloud.githubusercontent.com/assets/8840187/14200264/4f86b0d4-f7f2-11e5-8628-e227d9a6b9c6.png">

**Comment by unicodeveloper** [comment]
Has this really been fixed already @andela-cvundi ?

**Comment by vickris** [comment]
Yes ..... The distance between the edit and delete icons is now reasonable. I think we can close the issue
