### ISSUE TITLE
Minify scripts (Javascript and css files)

### ISSUE THREAD

**Issue by johnkariuki** [andela/suyabay#243]
Suyabay takes too long to load.
We currently have too many javascript and CSS files. (At least one js file for every js dependent feature)

This task will seek to :-
1. minify all javascript and css files.
2. Update the templates to use the minified versions
3. Update the wiki to direct users on how to go about making js changes and updating the minified scripts.

**Comment by johnkariuki** [comment]
@andela-araimi @andela-tolotin @unicodeveloper @andela-cvundi 
All js files are now minified into `public/js/scripts.js`.

Check out the [wiki](https://github.com/andela/suyabay/wiki) on the gulp tasks section to understand how to add a new js file into the minified script.

I have also tested out that the minification does not break anything to the best of my ability and everything is golden. 

Let me know if you notice any javascript dependent features that may be broken.

**Comment by unicodeveloper** [comment]
Now the sidebar doesn't show on the admin dashboard. Please look into this @andela-jkariuki

**Comment by johnkariuki** [comment]
Let me check it out and get back to you @unicodeveloper

**Comment by johnkariuki** [comment]
@unicodeveloper I have fixed the issue.
We now have this on the admin page

<img width="1436" alt="screen shot 2016-03-31 at 20 39 03" src="https://cloud.githubusercontent.com/assets/16223627/14185126/21827860-f781-11e5-92a7-557e84433040.png">
