### ISSUE TITLE
[Suyabay] The Platform needs a logo

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#28]

**Comment by unicodeveloper** [comment]
@andela-fokosun take care of this, you can meet @andela-abankole for assistance

**Comment by unicodeveloper** [comment]
@andela-fokosun what's the status on this?

**Comment by fokosun** [comment]
The Logo has been created, i will add it on the project now and send a PR

**Comment by unicodeveloper** [comment]
Alright add it and send it in the PR that you already raised!
