### ISSUE TITLE
The signUp button and the checkbox for remember me is not well aligned

### ISSUE THREAD

**Issue by ademola-raimi** [andela/suyabay#311]
The signUp button and the checkbox for `remember me` are not well aligned. The signUp button is too close to the password field.

![screen shot 2016-06-14 at 1 37 53 pm](https://cloud.githubusercontent.com/assets/14159420/16042997/742fb638-3235-11e6-8aa1-e1ca03952599.png)

**Comment by andela-araimi** [comment]
The signUp button and the checkbox for `remember me` are not well aligned. The signUp button is too close to the password field.

![screen shot 2016-06-14 at 1 37 53 pm](https://cloud.githubusercontent.com/assets/14159420/16042997/742fb638-3235-11e6-8aa1-e1ca03952599.png)
