### ISSUE TITLE
Homepage contents should be fetched from the database

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#34]
We should have all the episodes in the database. @andela-fokosun what's the status on this?

**Comment by fokosun** [comment]
PR sent

**Comment by unicodeveloper** [comment]
Any reason why there are no episodes @andela-fokosun ?

<img width="1280" alt="screen shot 2015-11-08 at 7 37 05 am" src="https://cloud.githubusercontent.com/assets/2946769/11019173/3ac81c46-85ec-11e5-9fbd-c486c8b6037f.png">
