### ISSUE TITLE
Social media authentication with Facebook and Twitter

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#35]
Users should be able to login with Facebook or Twitter

**Comment by unicodeveloper** [comment]
This feature has not been implemented yet @andela-iadeniyi what's the status on this?

**Comment by ibonly** [comment]
99.999% done. The only issue I think I will have is on facebook authentication because I had to edit facebookprovider.php in vendor/laravel/socialite/ for it to work locally.

**Comment by unicodeveloper** [comment]
Why did you have to edit the facebookprovider.php, I have never had to do that personally?

**Comment by ibonly** [comment]
I'm getting undefined first_name error, and to resolve it I have to edit facebookprovider. I tried resolving it without editing the file with Kola but no success. I also informed Nandaa about it.

**Comment by unicodeveloper** [comment]
Can i close this now @andela-iadeniyi ?. Is this issue fully resolved?

**Comment by ibonly** [comment]
Yes, you can close it. The issue has been resolved.
