### ISSUE TITLE
This is the registration/signup error dialog box. The error should be about registration not login

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#47]
<img width="1271" alt="screen shot 2015-10-26 at 5 59 05 pm" src="https://cloud.githubusercontent.com/assets/2946769/10736298/7a5c9da8-7c0c-11e5-9620-18a66f8a8e3f.png">

**Comment by unicodeveloper** [comment]
@andela-eosuagwu what's happening here?. This bug has still not been fixed. Any reason why?

**Comment by emeka-osuagwu** [comment]
This issue has already been fixed in my last pull PR
