### ISSUE TITLE
Password reset doesn't work

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#52]
<img width="1279" alt="screen shot 2015-10-27 at 2 14 34 pm" src="https://cloud.githubusercontent.com/assets/2946769/10759077/99afb70e-7cb5-11e5-9687-78559539f5d7.png">

**Comment by unicodeveloper** [comment]
When i try to do a password reset, this is all i get

**Comment by ibonly** [comment]
Yes, I am rectifying the issue.
