### ISSUE TITLE
Wrong placeholder

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#62]
Shouldn't that be `Confirm Password` ?. Please Change `Oh Snap!` to `Password Reset`
<img width="1271" alt="screen shot 2015-11-08 at 7 47 19 am" src="https://cloud.githubusercontent.com/assets/2946769/11019186/0049ea1c-85ed-11e5-94a0-c4bb9d78dfd5.png">

**Comment by fokosun** [comment]
Working on that and other major changes like overhauling the typography, adding facebook button login on signup page, etc

**Comment by unicodeveloper** [comment]
When will you be done with that?

**Comment by fokosun** [comment]
A couple of minutes time
