### ISSUE TITLE
Check if the user is loggedin already or not to know whether to display the login button with that message or not

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#94]
<img width="1119" alt="screen shot 2015-12-14 at 7 02 36 pm" src="https://cloud.githubusercontent.com/assets/2946769/11789221/5bbcb3ce-a295-11e5-867c-2b09c3f795f5.png">

**Comment by ibonly** [comment]
Okay, I will update it

**Comment by unicodeveloper** [comment]
This been taken care of?

**Comment by ibonly** [comment]
Yes
