### ISSUE TITLE
A normal user shouldn't see the dashboard when He or She navigate to /dashboard route

### ISSUE THREAD

**Issue by emeka-osuagwu** [andela/suyabay#97]
![screenshot from 2015-12-15 16 02 15](https://cloud.githubusercontent.com/assets/13197724/11814188/c505301c-a345-11e5-99da-bedaf3cf570c.png)

**Comment by unicodeveloper** [comment]
Lol..I am suprised this was not taken care of @andela-iadeniyi ???

**Comment by unicodeveloper** [comment]
Thats a simple middleware check there
