### ISSUE TITLE
When I log out, i can still access the dashboard route 

### ISSUE THREAD

**Issue by unicodeveloper** [andela/suyabay#98]
There should be a middleware that checks for this to prevent access to every route apart from the landing page, login and signup routes if a user is not logged in

<img width="1116" alt="screen shot 2015-12-15 at 5 25 53 pm" src="https://cloud.githubusercontent.com/assets/2946769/11816512/fabfc8d8-a350-11e5-9a13-7ec4f54b75e0.png">

**Comment by ibonly** [comment]
I have fixed it in the latest pull request.
